pipeline:
  name: event-5
  identifier: event5
  tags: {}
  projectIdentifier: AdithyaTest
  orgIdentifier: default
  stages:
    - stage:
        name: dd
        identifier: dd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_2
                  spec:
                    duration: 10m
        tags: {}
